"""@package rad.py
Python configuration file.

The file is auto-generated by cmake. It contains versioning information and file system IO path configuration.
"""

RAD_VERSION = "1.4.0"
RAD_DATA_DIR = "/home/ntelispak/workspace/rad/data"
RAD_TEMP_DIR = "/home/ntelispak/workspace/rad/tmp"
